# coding=utf-8 
# commentCreate
# commentQueryNew
# commentQueryNext
# f = urllib.urlopen("http://182.92.243.187:1234/commentQueryUpdated/",params)
# f = urllib.urlopen("http://182.92.243.187:1234/locationQuery/")
# f = urllib.urlopen("http://182.92.243.187:1234/locationUpdate",params)
# f = urllib.urlopen("http://182.92.243.187:1234/locationUpdate/",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentCreate",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentLike",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNew",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNew",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNewById",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNext",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNext",params)
# f = urllib.urlopen("http://localhost:1234/commentQueryNextById",params)
# f = urllib.urlopen("http://localhost:1234/groupCreate",params)
# f = urllib.urlopen("http://localhost:1234/groupCreate",params)
# f = urllib.urlopen("http://localhost:1234/groupCreate",params)
# f = urllib.urlopen("http://localhost:1234/groupDegrade/",params)
# f = urllib.urlopen("http://localhost:1234/groupExist/",params)
# f = urllib.urlopen("http://localhost:1234/groupQuery",params)
# f=urllib.urlopen("http://localhost:1234/locationQuery")
import urllib
import json

params = urllib.urlencode({'gender' : 1, 'location' : "Beijing", "content" : "", "face" : "1.jpg"})
f = urllib.urlopen("http://localhost:3000/newface", params)
print f.read()

params = urllib.urlencode({})
f = urllib.urlopen("http://localhost:3000/getRecentFace", params)
print f.read()
# params = urllib.urlencode({'gender' : 1, 'location' : "Beijing", "content" : "", "face" : "1.jpg"})
# f = urllib.urlopen("http://localhost:3000/newface", params)
# print f.read()

# params = urllib.urlencode({'gender' : 1, 'location' : "Beijing", "content" : "", "face" : "1.jpg"})
# f = urllib.urlopen("http://localhost:3000/newface", params)
# print f.read()
